import { Inter } from "next/font/google";
import "./globals.css";
import MuiThemeProvider from "./ThemeProvider"; // Import the custom theme provider
import SessionWrapper from "./components/SessionWrapper";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <SessionWrapper>
      <html lang="en">
        <body className={inter.className}>
          <MuiThemeProvider>{children}</MuiThemeProvider>
        </body>
      </html>
    </SessionWrapper>
  );
}
